package "BUS SMART" {
    
    package "Driver" {
        [Điểm danh]
        [Gửi thông báo]
        [Thông báo sự cố]
    }

    package "School" {
        [Quản lý chuyến]
        [Quản lý lịch]
    }

    package "Parents" {
        [Thông báo đổi địa điểm]
        [Lịch sử chuyến đi]
        [Huỷ chuyến]
    }
}